#!/usr/bin/env python3
"""Audit M6 local artifacts and create documentation drafts. Python 3.8+, ffprobe.

Does NOT change C++ source, videos, README.md, .gitignore, Git, or final reports.
Only autogenerated files in result/task3_audit/ are replaced on each run.
No third-party Python packages. All observations come from the local M6 logs.
"""
from __future__ import annotations

import argparse
import csv
import hashlib
import json
import math
import os
import re
import shutil
import subprocess
import sys
import tempfile
from collections import Counter
from datetime import datetime
from fractions import Fraction
from pathlib import Path
from typing import Any, Dict, List, Optional

FIELDS = (
    'frame,video_time_s,r_state,r_reason,valid_candidates,target_id,track_state,'
    'event,reason,lost_frames,lock_active,selected_index,r_x,r_y,target_x,target_y,'
    'target_radius,dx_img,dy_img,distance_px,angle_rad,angle_deg,angle_error_deg'
).split(',')
KEY_EVENTS = {'ACQUIRED', 'LOST', 'REACQUIRED', 'RELEASED'}
OBS_FIELDS = ('target_x', 'target_y', 'target_radius', 'dx_img', 'dy_img',
              'distance_px', 'angle_rad', 'angle_deg')
VIDEOS = ('task_3', 'task_4')
SCENES = {'task_3': '小能量机关', 'task_4': '大能量机关'}


class AuditError(RuntimeError):
    pass


def require(condition: bool, message: str) -> None:
    if not condition:
        raise AuditError(message)


def finite(value: str, name: str) -> float:
    try:
        number = float(value)
    except (TypeError, ValueError) as exc:
        raise AuditError(f'{name}: 缺少有效数值 ({value!r})') from exc
    require(math.isfinite(number), f'{name}: 非有限数值')
    return number


def integer(value: str, name: str) -> int:
    try:
        return int(value)
    except (TypeError, ValueError) as exc:
        raise AuditError(f'{name}: 不是整数 ({value!r})') from exc


def run_command(args: List[str], timeout: int = 300) -> str:
    try:
        completed = subprocess.run(args, capture_output=True, text=True,
                                   encoding='utf-8', errors='replace', timeout=timeout)
    except (OSError, subprocess.TimeoutExpired) as exc:
        raise AuditError(f'运行失败: {args[0]}: {exc}') from exc
    require(completed.returncode == 0,
            f'{args[0]} 退出码 {completed.returncode}: {completed.stderr.strip()[:1500]}')
    # ffprobe may report decoder errors on stderr and still return zero.
    if args[0].endswith('ffprobe'):
        require(not completed.stderr.strip(),
                f'ffprobe 报告错误，不能判为通过: {completed.stderr.strip()[:1500]}')
    return completed.stdout


def probe_video(path: Path) -> Dict[str, Any]:
    """Decode every video frame via ffprobe; collect dimensions and playback PTS."""
    require(path.is_file(), f'视频不存在: {path}')
    before = path.stat()
    fields = ('stream=width,height,avg_frame_rate,time_base,nb_frames,duration:'
              'frame=width,height,best_effort_timestamp_time,pts_time')
    text = run_command([
        'ffprobe', '-v', 'error', '-select_streams', 'v:0', '-show_frames',
        '-show_streams', '-show_entries', fields, '-of', 'json', str(path)
    ])
    try:
        data = json.loads(text)
        stream = data['streams'][0]
        fps = float(Fraction(stream['avg_frame_rate']))
        tick = float(Fraction(stream['time_base']))
        width, height = int(stream['width']), int(stream['height'])
        frames = data['frames']
    except (ValueError, KeyError, IndexError, TypeError, ZeroDivisionError) as exc:
        raise AuditError(f'视频参数不可用: {path.name}: {exc}') from exc
    require(fps > 0 and math.isfinite(fps), f'{path.name}: 无有效 FPS')
    require(width > 0 and height > 0 and frames, f'{path.name}: 无有效画面')
    times = []
    for i, frame in enumerate(frames):
        require(frame.get('width') == width and frame.get('height') == height,
                f'{path.name} 第 {i} 帧尺寸变化')
        value = frame.get('best_effort_timestamp_time', frame.get('pts_time'))
        times.append(finite(value, f'{path.name} 第 {i} 帧时间戳'))
    require(all(b > a for a, b in zip(times, times[1:])),
            f'{path.name}: 播放时间戳不严格递增')
    normalized = [t - times[0] for t in times]
    tolerance = max(0.0001, 2 * tick)
    # Current M6 VideoWriter is constant-frame-rate; flag variable timing rather
    # than silently treating average FPS as capture times.
    deviations = [abs(t - i / fps) for i, t in enumerate(normalized)]
    cfr = max(deviations, default=0.0) <= tolerance
    after = path.stat()
    require((before.st_size, before.st_mtime_ns) == (after.st_size, after.st_mtime_ns),
            f'{path.name}: 检查期间文件仍在变化，请等 M6 完成后重试')
    return dict(path=str(path), width=width, height=height, fps=fps,
                decoded_frames=len(frames), video_seconds=len(frames) / fps,
                bytes=after.st_size, metadata_frames=stream.get('nb_frames'),
                timestamp_tolerance=tolerance, constant_frame_rate=cfr,
                normalized_timestamps=normalized,
                max_cfr_deviation_s=max(deviations, default=0.0))


def compare_video(source: Dict[str, Any], output: Dict[str, Any]) -> Dict[str, Any]:
    for key in ('width', 'height', 'decoded_frames'):
        require(source[key] == output[key],
                f"{Path(output['path']).name}: {key} 不同: {source[key]} / {output[key]}")
    require(source['constant_frame_rate'],
            '输入不是本检查所支持的固定帧率时序；不能沿用 M6 固定 FPS 写入作为完整时序证明')
    require(output['constant_frame_rate'], '输出存在非固定帧率时序')
    require(abs(source['fps'] - output['fps']) <= 0.001, '输入输出 FPS 不一致')
    difference = max(abs(a - b) for a, b in zip(
        source['normalized_timestamps'], output['normalized_timestamps']))
    tolerance = max(source['timestamp_tolerance'], output['timestamp_tolerance'])
    require(difference <= tolerance, '输入输出相对播放时间戳不同')
    return {'status': 'PASS', 'max_timestamp_difference_s': difference,
            'tolerance_s': tolerance,
            'scope': '尺寸、解码帧数、FPS、相对播放时序；不证明图像内容或身份正确'}


def read_csv(path: Path) -> List[Dict[str, str]]:
    require(path.is_file(), f'缺少日志: {path}')
    with path.open(encoding='utf-8-sig', newline='') as file:
        reader = csv.DictReader(file)
        require(reader.fieldnames == FIELDS,
                f'{path.name}: 与 M6 的 23 列日志格式不符，请勿拿参考 replay.csv 代替本机 tracking.csv')
        rows = list(reader)
    for i, row in enumerate(rows):
        require(None not in row and all(v is not None for v in row.values()),
                f'{path.name} 数据行 {i}: 列数错误')
    return rows


def parse_summary(path: Path) -> Dict[str, Any]:
    require(path.is_file(), f'缺少 {path.name}；M6 可能尚未正常结束')
    text = path.read_text(encoding='utf-8')
    block = re.search(r'## 实际参数\s*(.*?)\s*## 身份与失败规则', text, re.S)
    require(block is not None, 'tracking_summary.md 缺少 M6 实际参数段')
    lost = re.search(r'Tracker maxLostFrames=(\d+)', block.group(1))
    count = re.search(r'完整处理帧数：\s*(\d+)', text)
    require(lost is not None and count is not None, '无法解析本机丢失门限或帧数')
    require(int(lost.group(1)) > 0, 'maxLostFrames 必须为正整数')
    totals = {key.strip(): int(value) for key, value in
              re.findall(r'^\|\s*([^|]+?)\s*\|\s*(\d+)\s*\|\s*$', text, re.M)}
    version = re.search(r'OpenCV：([^；\n]+)', text)
    return dict(text=text, parameters=block.group(1).strip(),
                max_lost=int(lost.group(1)), frames=int(count.group(1)),
                totals=totals, opencv=version.group(1) if version else '未记录')


def audit_tracking(rows: List[Dict[str, str]], source: Dict[str, Any],
                   max_lost: int) -> Dict[str, Any]:
    """Validate exact M6 logging/state invariants, NOT physical target identity."""
    require(len(rows) == source['decoded_frames'],
            f"tracking.csv 行数 {len(rows)} != 输入解码帧数 {source['decoded_frames']}")
    require(max_lost > 0, '无效丢失阈值')
    active_id: Optional[int] = None
    latest_id = 0
    failures = 0
    states: Counter = Counter()
    events: Counter = Counter()
    reasons: Counter = Counter()
    r_detected = multi = reorder_count = 0
    previous: Optional[Dict[str, str]] = None
    expected_events = []
    for index, row in enumerate(rows):
        tag = f'frame {index}'
        require(integer(row['frame'], tag) == index, f'{tag}: 帧号必须从 0 连续增加')
        require(abs(finite(row['video_time_s'], tag) - index / source['fps']) < 0.0001,
                f'{tag}: 日志播放时刻与输入 FPS 不匹配')
        state, event = row['track_state'], row['event']
        require(state in ('waiting', 'detected', 'lost'), f'{tag}: 未知跟踪状态')
        require(row['r_state'] in ('detected', 'lost'), f'{tag}: 未知 R 状态')
        valid = integer(row['valid_candidates'], tag)
        misses = integer(row['lost_frames'], tag)
        require(valid >= 0 and misses >= 0, f'{tag}: 非法负数计数')
        require(row['lock_active'] in ('0', '1'), f'{tag}: 非法 lock_active')
        locked = row['lock_active'] == '1'
        current_id = integer(row['target_id'], tag) if row['target_id'] else None
        rd = row['r_state'] == 'detected'
        if rd:
            rx, ry = finite(row['r_x'], tag), finite(row['r_y'], tag)
            require(0 <= rx < source['width'] and 0 <= ry < source['height'],
                    f'{tag}: R 坐标越界')
        else:
            require(not row['r_x'] and not row['r_y'] and valid == 0,
                    f'{tag}: R 丢失时不应报告 R 坐标或有效相对候选')
        if state == 'detected':
            require(rd and valid > 0 and locked and current_id is not None,
                    f'{tag}: detected 缺少当前 R/候选/锁定/ID')
            require(misses == 0 and integer(row['selected_index'], tag) >= 0,
                    f'{tag}: detected 的丢失计数或候选序号错误')
            values = {key: finite(row[key], f'{tag} {key}') for key in OBS_FIELDS}
            x, y = values['target_x'], values['target_y']
            require(0 <= x < source['width'] and 0 <= y < source['height'],
                    f'{tag}: 目标坐标越界')
            require(values['target_radius'] > 0 and values['distance_px'] > 0,
                    f'{tag}: 目标半径或中心距离无效')
            dx, dy = x - rx, y - ry
            require(abs(values['dx_img'] - dx) < 0.01 and
                    abs(values['dy_img'] - dy) < 0.01, f'{tag}: 相对坐标与 R 不一致')
            require(abs(values['distance_px'] - math.hypot(dx, dy)) < 0.02,
                    f'{tag}: 中心距离与坐标不一致')
            angle = math.atan2(-dy, dx)
            difference = math.remainder(values['angle_rad'] - angle, 2 * math.pi)
            require(abs(difference) < 0.0001, f'{tag}: 角度未按当前 R 正确计算')
            require(abs(values['angle_deg'] - math.degrees(values['angle_rad'])) < 0.0001,
                    f'{tag}: 弧度与角度单位转换不一致')
            if event == 'ACQUIRED':
                require(active_id is None and current_id == latest_id + 1,
                        f'{tag}: 未释放就新建 ID，或新 ID 非顺序递增')
                require(not row['angle_error_deg'], f'{tag}: 首次锁定不应有匹配误差')
                active_id, latest_id = current_id, current_id
            else:
                require(current_id == active_id, f'{tag}: 未新建却改变了 ID')
                require(event == ('REACQUIRED' if failures else 'TRACKED'),
                        f'{tag}: 恢复/连续跟踪事件与前序状态不一致')
                require(finite(row['angle_error_deg'], tag) >= 0,
                        f'{tag}: 匹配角度误差无效')
            failures = 0
        else:
            require(not row['selected_index'] and not row['angle_error_deg'] and
                    all(not row[key] for key in OBS_FIELDS),
                    f'{tag}: lost/waiting 时仍输出目标位置或角度，可能使用了陈旧结果')
            if state == 'waiting':
                require(active_id is None and current_id is None and not locked and
                        misses == 0 and event == 'NONE', f'{tag}: waiting 状态不一致')
                require(not rd or valid == 0, f'{tag}: 有有效候选却仍 waiting')
                failures = 0
            else:
                require(active_id is not None and current_id == active_id,
                        f'{tag}: lost 不应凭空出现或改变旧 ID')
                failures += 1
                require(misses == failures, f'{tag}: 连续丢失计数错误')
                if failures == max_lost:
                    require(event == 'RELEASED' and not locked, f'{tag}: 未按设定门限释放')
                    active_id = None
                    failures = 0
                else:
                    require(failures < max_lost and locked and
                            event == ('LOST' if failures == 1 else 'HOLD'),
                            f'{tag}: 过早释放、延迟释放或错误的等待事件')
        if (previous and state == 'detected' and previous['track_state'] == 'detected'
                and current_id == (int(previous['target_id']) if previous['target_id'] else None)
                and row['selected_index'] != previous['selected_index']):
            reorder_count += 1
        states[state] += 1
        events[event] += 1
        if state != 'detected':
            reasons[row['reason']] += 1
        r_detected += int(rd)
        multi += int(valid >= 2)
        if event in KEY_EVENTS:
            expected_events.append(row)
        previous = row
    return dict(states=dict(states), events=dict(events), failure_reasons=dict(reasons),
                r_detected=r_detected, multi_candidate_frames=multi,
                index_changes_same_id=reorder_count, expected_events=expected_events)


def verify_summary(summary: Dict[str, Any], logs: Dict[str, Any], frames: int) -> None:
    require(summary['frames'] == frames, 'tracking_summary.md 的帧数与视频不一致')
    pairs = {'detected': logs['states'].get('detected', 0),
             'lost': logs['states'].get('lost', 0),
             'waiting': logs['states'].get('waiting', 0),
             'R detected': logs['r_detected'],
             '至少两个有效候选的帧': logs['multi_candidate_frames'],
             '新建 ID / ACQUIRED': logs['events'].get('ACQUIRED', 0),
             '同 ID 恢复 / REACQUIRED': logs['events'].get('REACQUIRED', 0),
             '释放 ID / RELEASED': logs['events'].get('RELEASED', 0)}
    for key, value in pairs.items():
        require(summary['totals'].get(key) == value,
                f'tracking_summary.md 统计不一致: {key}，可能混入旧运行文件')


def audit_one(root: Path, name: str) -> Dict[str, Any]:
    result: Dict[str, Any] = dict(name=name, scene=SCENES[name], status='FAIL', errors=[], warnings=[])
    folder = root / 'result' / 'task3_windmill' / name
    try:
        print(f'[{name}] 解码输入与标注视频，并核对日志...', flush=True)
        source = probe_video(root / 'resources' / (name + '.mp4'))
        result['input'] = source
        overlay = probe_video(folder / 'recognition_overlay.mp4')
        result['overlay'] = overlay
        result['video_check'] = compare_video(source, overlay)
        binary_path = folder / 'binary_process.mp4'
        if binary_path.is_file():
            binary = probe_video(binary_path)
            result['binary'] = binary
            result['binary_check'] = compare_video(source, binary)
        else:
            result['warnings'].append('没有 binary_process.mp4；这是讲义建议项，不据此判必交材料缺失')
        summary = parse_summary(folder / 'tracking_summary.md')
        rows = read_csv(folder / 'tracking.csv')
        logs = audit_tracking(rows, source, summary['max_lost'])
        events = read_csv(folder / 'tracking_events.csv')
        require(events == logs.pop('expected_events'), 'tracking_events.csv 与逐帧日志事件不一致')
        verify_summary(summary, logs, source['decoded_frames'])
        result.update(summary=summary, rows=rows, logs=logs, status='PASS')
    except (AuditError, OSError, ValueError) as exc:
        result['errors'].append(str(exc))
    return result


def md_escape(value: Any) -> str:
    return str(value).replace('|', '\\|').replace('\n', ' ')


def compact_result(item: Dict[str, Any]) -> Dict[str, Any]:
    # Remove large per-frame structures from the JSON summary; original logs remain.
    value = dict(item)
    value.pop('rows', None)
    for key in ('input', 'overlay', 'binary'):
        if key in value:
            value[key] = {k: v for k, v in value[key].items() if k != 'normalized_timestamps'}
            value[key]['path'] = Path(value[key]['path']).name
    if 'summary' in value:
        value['summary'] = {k: v for k, v in value['summary'].items() if k != 'text'}
    return value


def candidate_windows(item: Dict[str, Any]) -> List[Dict[str, Any]]:
    rows = item.get('rows', [])
    if not rows:
        return []
    selected: List[Dict[str, Any]] = []
    # Longest contiguous same-ID detected segment with >=2 valid candidates.
    best_start = best_end = run_start = -1
    for i, row in enumerate(rows):
        matches = row['track_state'] == 'detected' and int(row['valid_candidates']) >= 2
        if matches:
            if run_start < 0 or (i > 0 and row['target_id'] != rows[i-1]['target_id']):
                run_start = i
            if i - run_start > best_end - best_start or best_start < 0:
                best_start, best_end = run_start, i
        else:
            run_start = -1
    if best_start >= 0:
        selected.append(dict(kind='双候选同 ID 日志片段', start=best_start, end=best_end,
                             frame=(best_start + best_end) // 2,
                             note='核对绿色圆是否始终对应同一有效目标，不能只看 ID 文本'))
    for event in ('REACQUIRED', 'ACQUIRED'):
        for row in [r for r in rows if r['event'] == event][:3]:
            i = int(row['frame'])
            selected.append(dict(kind=event, start=max(0, i-12), end=min(len(rows)-1, i+12),
                                 frame=i, note='核对前后真实目标是否相同、是否持续有效'))
    for row in [r for r in rows if r['event'] == 'RELEASED']:
        i = int(row['frame'])
        selected.append(dict(kind='RELEASED', start=max(0, i-item['summary']['max_lost']-3),
                             end=min(len(rows)-1, i+12), frame=i,
                             note='程序原因 '+row['reason']+'；人工区分熄灭/遮挡/漏检/误关联'))
    for i in range(1, len(rows)):
        a, b = rows[i-1], rows[i]
        if (a['track_state'] == b['track_state'] == 'detected' and a['target_id'] == b['target_id']
                and a['selected_index'] != b['selected_index']):
            selected.append(dict(kind='候选序号变、ID 未变', start=max(0, i-3),
                                 end=min(len(rows)-1, i+3), frame=i,
                                 note='序号变化本身不等于物理身份保持，需要看画面'))
            break
    return selected


def build_review(items: List[Dict[str, Any]]) -> str:
    lines = ['# 人工复查导航（自动从本机日志提取，不是正确性结论）', '',
             '先正常速度完整观看两个标注视频，再按下表回看原视频与标注视频。',
             '帧号从 0 开始；秒数是播放定位时间，不是现场采集时间。',
             '一个 ID 不变仍可能跟错实体；释放事件也不能证明目标确实熄灭。', '']
    for item in items:
        lines += ['## '+item['name'], '']
        if item['status'] != 'PASS':
            lines += ['结构检查尚未通过，先修复：'+'；'.join(item['errors']), '']
            continue
        lines += ['| 日志线索 | 关键帧 | 回看帧范围 | 回看播放时间/s | 人工检查 |',
                  '|---|---:|---|---|---|']
        fps = item['input']['fps']
        for win in candidate_windows(item):
            lines.append(f"| {win['kind']} | {win['frame']} | {win['start']}–{win['end']} | "
                         f"{win['start']/fps:.3f}–{win['end']/fps:.3f} | {win['note']} |")
        lines += ['', '人工复查结果请写入 `result/task3_tracking_result.md`，不要写在此自动文件里。', '']
    return '\n'.join(lines)+'\n'


def build_audit(items: List[Dict[str, Any]], environment: Dict[str, str]) -> str:
    lines = ['# Milestone 7 本机结构性核验', '',
             '本文件由本机输入、输出视频和 M6 日志生成。每次重新运行会替换本自动文件。',
             '**PASS 仅表示这里执行的结构性检查通过，不代表识别准确、物理身份正确或整份作业验收通过。**', '',
             '| 输入 | 状态 | 输入/标注解码帧数 | 尺寸/FPS |', '|---|---|---|---|']
    for item in items:
        a, b = item.get('input', {}), item.get('overlay', {})
        lines.append(f"| {item['name']} | {item['status']} | {a.get('decoded_frames','—')}/{b.get('decoded_frames','—')} | "
                     f"{a.get('width','—')}×{a.get('height','—')} / {a.get('fps','—')} |")
    lines += ['', '| 视频 | 文件 | 实际大小 / MiB |', '|---|---|---:|']
    for item in items:
        for key in ('input', 'overlay', 'binary'):
            if key in item:
                media = item[key]
                lines.append(f"| {item['name']} | {Path(media['path']).name} | {media['bytes']/1048576:.3f} |")
    for item in items:
        lines += ['', '## '+item['name'], '']
        if item['errors']:
            lines += ['错误：'+md_escape(x) for x in item['errors']]
        lines += ['提示：'+x for x in item['warnings']]
        if item['status'] == 'PASS':
            lines += ['输入和标注：全帧可解码、尺寸一致、FPS 一致、相对播放时间戳一致。',
                      '逐帧日志：帧号连续；有效观测使用当前 R；失败帧位置为空；ID 与丢失/释放规则一致。',
                      '事件日志与摘要统计和 tracking.csv 相符。',
                      '这些检查不能证明画面内容没有重复/错序，也不能判断绿色圆是否始终是同一物理目标。']
    lines += ['', '## 当前环境（不是历史运行环境证明）', '']
    for key, value in environment.items():
        lines.append(f'- {key}: `{value}`')
    lines += ['', '检测时的 OpenCV 版本和运行参数来自各视频的 tracking_summary.md。',
              'manifest.json 的 SHA256 是检查时的快照，不是源码与旧视频自动匹配的证明。',
              '修改源码或参数后需重新编译、重跑两个视频，再重新运行本工具。', '']
    return '\n'.join(lines)


def build_report(items: List[Dict[str, Any]]) -> str:
    lines = ['# 任务 3：真实能量机关识别与稳定跟踪（本机报告草稿）', '',
             '> 本稿根据当前本机文件自动整理。先复制到 `result/task3_tracking_result.md` 再编辑。',
             '> 下列链接按最终报告位置计算。提交前填写所有【待人工填写】，核对方法与最终源码一致。', '',
             '## 1. 输入与任务范围', '',
             '使用发放的 task_3.mp4、task_4.mp4，分别对应小能量机关与大能量机关，文件放入 resources/。',
             '使用同一个 C++17 / OpenCV 程序处理两段素材。真实视频不做现场角速度拟合，日志时间仅为播放时刻。', '',
             '| 视频 | 场景 | 尺寸 | FPS | 输入解码帧数 | 标注解码帧数 | 结构检查 |',
             '|---|---|---|---:|---:|---:|---|']
    for item in items:
        a, b = item.get('input', {}), item.get('overlay', {})
        lines.append(f"| {item['name']}.mp4 | {item['scene']} | {a.get('width','—')}×{a.get('height','—')} | "
                     f"{a.get('fps','—')} | {a.get('decoded_frames','—')} | {b.get('decoded_frames','—')} | {item['status']} |")
    lines += ['', '仅在上表 PASS 时，可表述本次尺寸、帧数、FPS 和相对播放时序核对通过；FAIL 时需先修复。',
              '不据此声称逐像素无损、音轨保留、定位准确或物理身份零错误。', '',
              '## 2. 检测与关联方法（依据 M3–M6 方案，需核对最终源码）', '',
              '颜色检测：BGR 转 HSV，范围分割后进行可选形态学处理，保留原始掩膜供结构检查。',
              '候选目标：霍夫圆粗选，再检查外环、内环和两环之间的空隙；圆环质量分数不是概率。',
              'R 检测：逐帧筛选小轮廓的面积、宽高、长宽比、颜色、邻域和与目标的距离关系，采用外接框中心估计 R 标中心。',
              '相对几何：dx=target_x-r_x，dy=target_y-r_y；theta=atan2(-dy,dx)。共同二维平移被相减消去，但未校正透视。',
              '稳定关联：首次按质量选一个有效候选；已有锁定后按相对角度、中心距离变化和目标小圆半径变化关联，'
              '不因另一个候选质量更高而抢选。短期图像角度增量仅作关联参考，不是物理运动预测结果。',
              'ID 表示连续锁定片段；释放后的新锁定使用新 ID，不是物理扇叶永久编号。', '',
              '## 3. 本机运行参数', '']
    for item in items:
        lines += ['### '+item['name'], '']
        if 'summary' not in item:
            lines += ['【待修复】未能读取本次完整 M6 运行记录。', '']
            continue
        summary = item['summary']
        lines += ['运行日志所记 OpenCV：`'+summary['opencv']+'`。', '',
                  '```text', summary['parameters'], '```', '']
        n = summary['max_lost']
        lines += [f'本次 maxLostFrames={n}：第 {n} 个连续失败帧释放；释放帧不立即重选，下一帧才允许新锁定。',
                  '未达门限时保留旧 ID；恢复关联为 REACQUIRED，保持旧 ID。R 失效也算无有效观测。',
                  '失败帧不删除，目标位置与角度字段留空，不用旧位置或关联参考冒充当前观测。', '']
    lines += ['## 4. 观测状态统计（不是准确率）', '',
              '| 视频 | detected | lost | waiting | 新建 ID | 同 ID 恢复 | 释放 ID |',
              '|---|---:|---:|---:|---:|---:|---:|']
    for item in items:
        log = item.get('logs')
        if not log:
            lines.append(f"| {item['name']} | — | — | — | — | — | — |")
            continue
        s, e = log['states'], log['events']
        lines.append(f"| {item['name']} | {s.get('detected',0)} | {s.get('lost',0)} | {s.get('waiting',0)} | "
                     f"{e.get('ACQUIRED',0)} | {e.get('REACQUIRED',0)} | {e.get('RELEASED',0)} |")
    lines += ['', '上述数量来自程序输出状态，不是人工真值；未标注真实目标，故不报告准确率、召回率、ID 切换率或“满分”。', '',
              '## 5. 人工复查与典型事件', '',
              '复查导航见 [自动生成的回看片段](task3_audit/manual_review_windows.md)。它只指出程序事件，不证明事件合理。', '',
              '| 检查项 | 视频与帧范围 | 对照原图观察到的事实 | 判定与原因 |',
              '|---|---|---|---|',
              '| 两目标同时有效时是否保持原目标 | 【待人工填写】 | 【待人工填写】 | 【待人工填写】 |',
              '| 短暂丢失后是否恢复同一实体和 ID | 【待人工填写】 | 【待人工填写】 | 【待人工填写】 |',
              '| 释放和重新选择是否合理 | 【待人工填写】 | 【待人工填写】 | 【待人工填写】 |',
              '| 至少一个已知漏检/误检/误关联例子 | 【待人工填写】 | 【待人工填写】 | 【待人工填写】 |', '',
              '当本次录像中未出现某类情形，应写清“本次未观察到”，不能编造成功例子。',
              '完整观看结论：【待人工填写：两个视频是否全程播放并对照原图，检查日期、发现的问题】。', '',
              '## 6. 局限与改进', '',
              '当前方法依赖颜色、圆环形状和经验门限；R/圆检测错误会传入跟踪器。',
              '强透视、灯光闪烁、相机突变、相似目标在相近方位、长时间丢失均有误关联风险。',
              'ID 文本不变并不证明物理身份始终正确。',
              '本机调整及效果：【待人工填写：参数、修改原因、复跑两个视频后的收益与代价；未调参如实填写】。', '',
              '## 7. 构建、运行与结果索引', '', '从项目根目录执行：', '', '```bash',
              'cmake -S . -B build', 'cmake --build build --target task3_windmill -j4',
              './build/task3_windmill resources/task_3.mp4 result/task3_windmill/task_3',
              './build/task3_windmill resources/task_4.mp4 result/task3_windmill/task_4', '```', '']
    for item in items:
        n = item['name']
        lines.append(f'- {n}：[标注视频](task3_windmill/{n}/recognition_overlay.mp4)、'
                     f'[本机运行记录](task3_windmill/{n}/tracking_summary.md)、'
                     f'[逐帧日志](task3_windmill/{n}/tracking.csv)、'
                     f'[事件日志](task3_windmill/{n}/tracking_events.csv)。')
    lines += ['', '[自动结构检查](task3_audit/audit.md)。输入来源为随作业发放的 resources/task_3.mp4 和 resources/task_4.mp4。',
              '素材或视频若改为附件/外部大文件交付，应在此与总 README 写明实际获取方式并验证可访问。', '']
    return '\n'.join(lines)


def build_readme(items: List[Dict[str, Any]]) -> str:
    lines = ['\n## 任务 3：真实能量机关识别与稳定跟踪', '',
             '任务 3 的识别和跟踪程序使用 C++17、OpenCV、CMake；沿用任务 1、2 的工程和根目录构建配置。',
             '独立核验脚本使用 Python 3 标准库与 ffprobe，不参与识别算法，不需要 pip/conda 环境。', '',
             '### 构建与运行', '', '在工程根目录执行：', '', '```bash',
             'cmake -S . -B build', 'cmake --build build --target task3_windmill -j4',
             './build/task3_windmill resources/task_3.mp4 result/task3_windmill/task_3',
             './build/task3_windmill resources/task_4.mp4 result/task3_windmill/task_4',
             'python3 tools/finalize_task3.py --root .', '```', '',
             '输入采用统一发放素材，放到 resources/；同一个可执行程序通过两个路径参数处理不同视频。',
             '参数位置：include/task3_windmill/detector.hpp、tracker.hpp；本次实际参数写在各自 tracking_summary.md。', '',
             '| 视频 | 场景 | 尺寸 | FPS | 解码帧数 |', '|---|---|---|---:|---:|']
    for item in items:
        a = item.get('input', {})
        lines.append(f"| {item['name']}.mp4 | {item['scene']} | {a.get('width','待核对')}×{a.get('height','待核对')} | "
                     f"{a.get('fps','待核对')} | {a.get('decoded_frames','待核对')} |")
    lines += ['', '### 输出与说明', '',
              '[任务 3 跟踪说明](result/task3_tracking_result.md)；'
              '[结构性核验](result/task3_audit/audit.md)。', '']
    for item in items:
        n = item['name']
        lines.append(f'- {n}：[完整标注视频](result/task3_windmill/{n}/recognition_overlay.mp4)、'
                     f'[运行参数与统计](result/task3_windmill/{n}/tracking_summary.md)、'
                     f'[逐帧日志](result/task3_windmill/{n}/tracking.csv)。')
        if 'binary' in item:
            lines.append(f'  [二值化过程](result/task3_windmill/{n}/binary_process.mp4)。')
    lines += ['', '检测状态与 ID 是程序输出，不据此宣称检测准确率或物理身份零错误。'
              '等待/丢失帧完整保留，失败时不把旧坐标绘制成当前有效目标。',
              '该章节是总 README 的追加内容，不替代任务 1 分析、任务 2 参数说明和全工程依赖。', '']
    return '\n'.join(lines)


def atomic_write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    require(not path.is_symlink(), f'拒绝写入符号链接: {path}')
    fd, temporary = tempfile.mkstemp(dir=str(path.parent), prefix='.audit_', suffix='.tmp')
    try:
        with os.fdopen(fd, 'w', encoding='utf-8') as file:
            file.write(text)
        os.replace(temporary, path)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)


def source_manifest(root: Path) -> Dict[str, Any]:
    paths = [root / 'CMakeLists.txt', root / 'tools' / 'finalize_task3.py']
    for relative in ('src/task3_windmill', 'include/task3_windmill'):
        paths.extend(p for p in (root / relative).rglob('*') if p.suffix in ('.cpp', '.hpp', '.h'))
    data = {}
    for path in sorted(set(paths)):
        if path.is_file():
            data[str(path.relative_to(root))] = hashlib.sha256(path.read_bytes()).hexdigest()
    return {'scope': '核验时源码快照；不自动证明视频由这些字节对应的可执行文件生成', 'sha256': data}


def environment_info() -> Dict[str, str]:
    values = {'Python': sys.version.split()[0]}
    for key, args in [('g++', ['g++', '--version']), ('CMake', ['cmake', '--version']),
                      ('Git', ['git', '--version']), ('ffprobe', ['ffprobe', '-version'])]:
        try:
            values[key] = run_command(args, 20).splitlines()[0]
        except (AuditError, IndexError):
            values[key] = '未能读取（本工具不会自动安装）'
    return values


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--root', type=Path, default=Path('.'), help='vision_training 工程根目录')
    args = parser.parse_args()
    root = args.root.resolve()
    require((root / 'resources').is_dir() and (root / 'result').is_dir(),
            '请在 vision_training 根目录运行，或用 --root 指定该目录')
    require(shutil.which('ffprobe') is not None,
            '缺少 ffprobe。先检查 ffprobe -version；Ubuntu 可按教程安装 ffmpeg 包')
    folder = root / 'result' / 'task3_audit'
    require(not folder.is_symlink(), '拒绝写入作为符号链接的 task3_audit 目录')
    # Store timestamps/sizes before auditing to catch concurrent M6 runs.
    watched = [p for p in (root / 'result' / 'task3_windmill').glob('task_*/*')
               if p.is_file() and p.suffix in ('.csv', '.md', '.mp4')]
    stamps = {p: (p.stat().st_size, p.stat().st_mtime_ns) for p in watched}
    items = [audit_one(root, name) for name in VIDEOS]
    for path, stamp in stamps.items():
        require(path.exists() and (path.stat().st_size, path.stat().st_mtime_ns) == stamp,
                '检查期间结果文件发生变化，请等待 M6 完成后重跑 M7')
    environment = environment_info()
    payload = {'generated_at': datetime.now().astimezone().isoformat(),
               'structural_status': 'PASS' if all(x['status'] == 'PASS' for x in items) else 'FAIL',
               'semantic_accuracy_assessed': False, 'environment': environment,
               'videos': [compact_result(x) for x in items]}
    atomic_write(folder / 'audit.json', json.dumps(payload, ensure_ascii=False, indent=2)+'\n')
    atomic_write(folder / 'audit.md', build_audit(items, environment))
    atomic_write(folder / 'manual_review_windows.md', build_review(items))
    atomic_write(folder / 'tracking_report.auto.md', build_report(items))
    atomic_write(folder / 'README_TASK3_APPEND.auto.md', build_readme(items))
    atomic_write(folder / 'manifest.json', json.dumps(source_manifest(root), ensure_ascii=False, indent=2)+'\n')
    print('\n自动文件已写入: result/task3_audit/')
    for item in items:
        print(f"{item['name']}: {item['status']}")
        for error in item['errors']:
            print('  '+error)
    if payload['structural_status'] == 'PASS':
        print('STRUCTURAL CHECKS PASSED — 仍需人工查看两个完整视频；不是识别准确率或作业总评。')
        return 0
    print('STRUCTURAL CHECKS FAILED — 请阅读 audit.md；不要把草稿当作已通过的最终报告。')
    return 1


if __name__ == '__main__':
    try:
        raise SystemExit(main())
    except (AuditError, OSError) as error:
        print('ERROR:', error, file=sys.stderr)
        raise SystemExit(2)
